version: "2.4"

networks:
    default:
      external:
        name: docker_default
services:
    elasticsearch:
        image: elasticsearch:7.5.2
        ports:
            - 9200:9200
            - 9300:9300
        environment: 
            - discovery.type=single-node
        healthcheck:
            test: ["CMD-SHELL", "curl -sSf http://elasticsearch:9200/_cat/health?v"]
            interval: 1s
            timeout: 1s
            retries: 30    
    grafana:
        image: grafana/grafana:6.6.0
        ports:
            - 3000:3000
#        user: "grafana"
#        healthcheck:
#            test: ["CMD-SHELL", "curl -sSfL http://grafana:3000"]
#            interval: 1s
#            timeout: 1s
#            retries: 30
        volumes:
            - ./vol-var-lib:/var/lib/grafana
        depends_on:
            elasticsearch:
                condition: service_healthy          
    pingfail1:
        image: qrkourier/pingfail
        build: .
        environment: 
            - PING_IPV="4"
            - PING_TGT="8.8.8.8"
        depends_on:
            elasticsearch:
                condition: service_healthy          
    pingfail2:
        image: qrkourier/pingfail
        build: .
        environment: 
            - PING_IPV="4"
            - PING_TGT="4.2.2.2"
        depends_on:
            elasticsearch:
                condition: service_healthy          
            
    